### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by 0xh3LL0** [Doddler/PrismArkTools#1]
i tried to build all the tools in this repo, all done successfully, except prismscriptsplit
here is the output and error:

1>------ Build started: Project: PrismScriptMerge, Configuration: Release Any CPU ------
1>d:\PrismArkTools-master\PrismScriptSplit\PrismScriptMerge\Program.cs(282,13,282,17): error CS1547: Keyword 'void' cannot be used in this context
1>d:\PrismArkTools-master\PrismScriptSplit\PrismScriptMerge\Program.cs(282,30,283,1):  error CS1528: Expected ; or = (cannot specify constructor arguments in declaration)
1>d:\PrismArkTools-master\PrismScriptSplit\PrismScriptMerge\Program.cs(282,30,282,31): error CS1003: Syntax error, '[' expected
1>d:\PrismArkTools-master\PrismScriptSplit\PrismScriptMerge\Program.cs(282,31,282,32): error CS1525: Invalid expression term ')'
1>d:\PrismArkTools-master\PrismScriptSplit\PrismScriptMerge\Program.cs(282,32,282,32): error CS1003: Syntax error, ']' expected
1>d:\PrismArkTools-master\PrismScriptSplit\PrismScriptMerge\Program.cs(282,32,282,32): error CS1002: ; expected
1>d:\PrismArkTools-master\PrismScriptSplit\PrismScriptMerge\Program.cs(359,44,359,45): error CS1003: Syntax error, ',' expected
1>d:\PrismArkTools-master\PrismScriptSplit\PrismScriptMerge\Program.cs(374,42,374,46): error CS1525: Invalid expression term 'uint'
1>d:\PrismArkTools-master\PrismScriptSplit\PrismScriptMerge\Program.cs(374,47,374,48): error CS1003: Syntax error, ',' expected
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

Severity	Code	Description						Project	File											Line	Suppression State
Error		CS0149	Method name expected					PrismScriptMerge	d:\PrismArkTools-master\PrismScriptSplit\PrismScriptMerge\Program.cs	343	Active
Error		CS1547	Keyword 'void' cannot be used in this context		PrismScriptMerge	d:\PrismArkTools-master\PrismScriptSplit\PrismScriptMerge\Program.cs	282	Active
Error		CS1528	Expected ; or = (cannot specify constructor arguments in declaration)	PrismScriptMerge	d:\PrismArkTools-master\PrismScriptSplit\PrismScriptMerge\Program.cs	282	Active
Error		CS1003	Syntax error, '[' expected				PrismScriptMerge	d:\PrismArkTools-master\PrismScriptSplit\PrismScriptMerge\Program.cs	282	Active
Error		CS1525	Invalid expression term ')'				PrismScriptMerge	d:\PrismArkTools-master\PrismScriptSplit\PrismScriptMerge\Program.cs	282	Active
Error		CS1003	Syntax error, ']' expected				PrismScriptMerge	d:\PrismArkTools-master\PrismScriptSplit\PrismScriptMerge\Program.cs	282	Active
Error		CS1002	; expected						PrismScriptMerge	d:\PrismArkTools-master\PrismScriptSplit\PrismScriptMerge\Program.cs	282	Active
Error		CS1003	Syntax error, ',' expected				PrismScriptMerge	d:\PrismArkTools-master\PrismScriptSplit\PrismScriptMerge\Program.cs	359	Active
Error		CS1525	Invalid expression term 'uint'				PrismScriptMerge	d:\PrismArkTools-master\PrismScriptSplit\PrismScriptMerge\Program.cs	374	Active
Error		CS1003	Syntax error, ',' expected				PrismScriptMerge	d:\PrismArkTools-master\PrismScriptSplit\PrismScriptMerge\Program.cs	374	Active
Error		CS0149	Method name expected					PrismScriptMerge	d:\PrismArkTools-master\PrismScriptSplit\PrismScriptMerge\Program.cs	303	Active
Error		CS0165	Use of unassigned local variable 'LocalAddWord'		PrismScriptMerge	d:\PrismArkTools-master\PrismScriptSplit\PrismScriptMerge\Program.cs	303	Active
Error		CS0149	Method name expected					PrismScriptMerge	d:\PrismArkTools-master\PrismScriptSplit\PrismScriptMerge\Program.cs	321	Active
Error		CS0103	The name 'var' does not exist in the current context	PrismScriptMerge	d:\PrismArkTools-master\PrismScriptSplit\PrismScriptMerge\Program.cs	359	Active
Error		CS0103	The name 'i' does not exist in the current context	PrismScriptMerge	d:\PrismArkTools-master\PrismScriptSplit\PrismScriptMerge\Program.cs	359	Active
Error		CS0103	The name 'j' does not exist in the current context	PrismScriptMerge	d:\PrismArkTools-master\PrismScriptSplit\PrismScriptMerge\Program.cs	374	Active

**Comment by Doddler** [comment]
Looking into it here, it looks like the issue is because a local function is used, which is a c# 6 feature. I believe you'd need to either use a version of visual studio that supports c# 6 (2015 or newer should?), or you could make a relatively simple edit to move the LocalAddWord function on line 282 out of the function and pass it the parameters needed.

**Comment by 0xh3LL0** [comment]
oh, i see...
guess i'll upgrade my vs then, i use vs 2015 update 2
